.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeSection4 - Debug ]----------"
	@cd "ChallengeSection4" && "$(MAKE)" -f  "ChallengeSection4.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeSection4 - Debug ]----------"
	@cd "ChallengeSection4" && "$(MAKE)" -f  "ChallengeSection4.mk" clean
